services:
  - type: web
    name: gameboxd
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn GameBoxd:app"
    envVars:
      - key: RAWG_API_KEY
        sync: false
